//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proact.Services.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_fr_FR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_fr_FR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Proact.Services.Resources.Resource.fr-FR", typeof(Resource_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string attachment_ready {
            get {
                return ResourceManager.GetString("attachment_ready", resourceCulture);
            }
        }
        
        internal static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        internal static string medical_team {
            get {
                return ResourceManager.GetString("medical_team", resourceCulture);
            }
        }
        
        internal static string new_broadcastmessage {
            get {
                return ResourceManager.GetString("new_broadcastmessage", resourceCulture);
            }
        }
        
        internal static string new_reply_from_medic {
            get {
                return ResourceManager.GetString("new_reply_from_medic", resourceCulture);
            }
        }
        
        internal static string new_reply_from_nurse {
            get {
                return ResourceManager.GetString("new_reply_from_nurse", resourceCulture);
            }
        }
        
        internal static string new_reply_from_patient {
            get {
                return ResourceManager.GetString("new_reply_from_patient", resourceCulture);
            }
        }
        
        internal static string new_survey_to_compile {
            get {
                return ResourceManager.GetString("new_survey_to_compile", resourceCulture);
            }
        }
        
        internal static string new_topic_from_patient {
            get {
                return ResourceManager.GetString("new_topic_from_patient", resourceCulture);
            }
        }
        
        internal static string new_reply_to_a_message {
            get {
                return ResourceManager.GetString("new_reply_to_a_message", resourceCulture);
            }
        }
    }
}
